import type { Metadata } from "next";
import localFont from "next/font/local";
import { Raleway, Cinzel } from "next/font/google";
import "./globals.css";

const raleway = Raleway({subsets: ["latin"], weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"], variable: "--font-raleway"});
const cinzel = Cinzel({subsets: ["latin"], weight:["400", "500", "600", "700", "800", "900"], variable: "--font-cinzel"});



export const metadata: Metadata = {
  title: "Cementizio - Revestimentos Modernos e Personalizados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${cinzel.variable} ${raleway.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
